CREATE TABLE IF NOT EXISTS urls (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS checks (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    response_statsus bigint NOT NULL,
    headers TEXT NOT NULL,
    description TEXT NOT NULL,
    title VARCHAR(255),
    created_at TIMESTAMP NOT NULL
);